In [34]:
import pandas as pd
import geopandas as gpd 
import requests 
import json
from datetime import datetime
from io import StringIO
import csv
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from shapely import wkt
from scipy.spatial.distance import cdist

import pandas as pd
import geopandas as gpd 
import requests 
import json
from datetime import datetime
from io import StringIO
import csv
import time
import os
import airqualityandclimateAPI
import statsmodels.api as sm

from statsmodels.stats.outliers_influence \
     import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
                         summarize,
                         poly)
from linearmodels import PanelOLS

In [15]:
from Analysis import *

In [19]:
totaldataframe = totaldata()

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:55: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  totaldf = pd.read_csv(totaldatapath)

In [20]:
# totaldata['YEAR'] = pd.to_datetime(totaldata['DATE']).dt.year
station_year_check = totaldataframe.groupby('CLIMATE_STATION_NAME')['YEAR'].nunique()
print(station_year_check)

CLIMATE_STATION_NAME
CHICAGO MIDWAY AIRPORT, IL US       10
CHICAGO PALWAUKEE AIRPORT, IL US    10
Name: YEAR, dtype: int64

# Model 1

In [21]:
xclimate = ['DailyAverageDryBulbTemperature', 'DailyAverageWindSpeed','DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindSpeed',
       'DailyPrecipitation','DailySustainedWindSpeed', 'DailySustainedWindDirection_sin', 'DailySustainedWindDirection_cos',
       'DailyAveragePrecipitation', 'DailyAveragePressureChange',
       'DailyAverageRelativeHumidity',]

y = ['arithmetic_mean']

fe = ['DATE','CLIMATE_STATION_NAME']

model_1_results = model_1(totaldataframe, xclimate, y, fe)
model_1_results

# table = pd.DataFrame({
#     "Coefficient": model_1_results.params,
#     "Std. Error": model_1_results.std_errors,
#     "t-stat": model_1_results.tstats,
#     "p-value": model_1_results.pvalues
# })

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DATE'] = pd.to_datetime(df['DATE'])
/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['YEAR'] = pd.to_numeric(df['DATE'].dt.year)

                                                index    coef  std err  \
0                                               const  2.4867   12.344
1                      DailyAverageDryBulbTemperature  0.3159    0.160
2                               DailyAverageWindSpeed  0.3232    0.393
3                      DailyMaximumDryBulbTemperature  0.1442    0.029
4                      DailyMinimumDryBulbTemperature -0.1126    0.029
5                                  DailyPeakWindSpeed -0.1548    0.151
6                                  DailyPrecipitation  0.0185    0.011
7                             DailySustainedWindSpeed -0.1946    0.236
8                     DailySustainedWindDirection_sin  0.1000    0.063
9                     DailySustainedWindDirection_cos -1.6705    0.030
10                          DailyAveragePrecipitation -0.1243    1.398
11                         DailyAveragePressureChange  0.7414    0.012
12                       DailyAverageRelativeHumidity  0.0580    0.130
13  CLIMATE_STATION_NAME_CHICAGO PALWAUKEE AIRPORT... -0.6907    0.012
14                                          YEAR_2017  0.1701    0.034
15                                          YEAR_2018  0.7637    0.049
16                                          YEAR_2019  0.4059    0.068
17                                          YEAR_2020 -0.0196    0.558
18                                          YEAR_2021  0.5410    0.251
19                                          YEAR_2022 -0.1415    0.399
20                                          YEAR_2023  1.9387    0.053
21                                          YEAR_2024 -1.2230    0.007
22                                          YEAR_2025 -2.6643    0.360

          z  P>|z|
0     0.201  0.840
1     1.971  0.049
2     0.823  0.410
3     4.982  0.000
4    -3.864  0.000
5    -1.026  0.305
6     1.643  0.100
7    -0.824  0.410
8     1.582  0.114
9   -54.981  0.000
10   -0.089  0.929
11   61.891  0.000
12    0.445  0.656
13  -55.410  0.000
14    4.938  0.000
15   15.457  0.000
16    6.003  0.000
17   -0.035  0.972
18    2.158  0.031
19   -0.355  0.723
20   36.599  0.000
21 -177.732  0.000
22   -7.405  0.000

/opt/anaconda3/lib/python3.13/site-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 22, but rank is 1
  warnings.warn('covariance of constraints does not have full '

,index,coef,std err,z,P>|z|
0,const,2.4867,12.344,0.201,0.840
1,DailyAverageDryBulbTemperature,0.3159,0.160,1.971,0.049
2,DailyAverageWindSpeed,0.3232,0.393,0.823,0.410
3,DailyMaximumDryBulbTemperature,0.1442,0.029,4.982,0.000
4,DailyMinimumDryBulbTemperature,-0.1126,0.029,-3.864,0.000
5,DailyPeakWindSpeed,-0.1548,0.151,-1.026,0.305
6,DailyPrecipitation,0.0185,0.011,1.643,0.100
7,DailySustainedWindSpeed,-0.1946,0.236,-0.824,0.410
8,DailySustainedWindDirection_sin,0.1000,0.063,1.582,0.114
9,DailySustainedWindDirection_cos,-1.6705,0.030,-54.981,0.000
10,DailyAveragePrecipitation,-0.1243,1.398,-0.089,0.929
11,DailyAveragePressureChange,0.7414,0.012,61.891,0.000
12,DailyAverageRelativeHumidity,0.0580,0.130,0.445,0.656
13,CLIMATE_STATION_NAME_CHICAGO PALWAUKEE AIRPORT...,-0.6907,0.012,-55.410,0.000
14,YEAR_2017,0.1701,0.034,4.938,0.000
15,YEAR_2018,0.7637,0.049,15.457,0.000
16,YEAR_2019,0.4059,0.068,6.003,0.000
17,YEAR_2020,-0.0196,0.558,-0.035,0.972
18,YEAR_2021,0.5410,0.251,2.158,0.031
19,YEAR_2022,-0.1415,0.399,-0.355,0.723
20,YEAR_2023,1.9387,0.053,36.599,0.000
21,YEAR_2024,-1.2230,0.007,-177.732,0.000
22,YEAR_2025,-2.6643,0.360,-7.405,0.000

In [22]:
model_1_table = model_1_results
model_1_table = model_1_table.rename(columns={'index':'Variable'})
model_1_table.reset_index(inplace=True)
model_1_table.head()

   index                        Variable    coef  std err      z  P>|z|
0      0                           const  2.4867   12.344  0.201  0.840
1      1  DailyAverageDryBulbTemperature  0.3159    0.160  1.971  0.049
2      2           DailyAverageWindSpeed  0.3232    0.393  0.823  0.410
3      3  DailyMaximumDryBulbTemperature  0.1442    0.029  4.982  0.000
4      4  DailyMinimumDryBulbTemperature -0.1126    0.029 -3.864  0.000

In [26]:
xenergy= ['DailyAverageDryBulbTemperature', 'DailyAverageWindSpeed',
        'DailyDepartureFromNormalAverageTemperature',
        'DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindSpeed',
       'DailyPrecipitation',
       'DailySustainedWindSpeed',
       'DailyPeakWindDirection_sin', 'DailyPeakWindDirection_cos',
       'DailySustainedWindDirection_sin', 'DailySustainedWindDirection_cos',
       'DailyAverageDewPointTemperature',
       'DailyAveragePrecipitation', 'DailyAveragePressureChange',
       'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure',
       'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature',
       'DailyAverageWindGustSpeed', 'DailyAverageWindDirection_sin',
       'DailyAverageWindDirection_cos']

xenergyandrenewables = xenergy + ['Number', 'Capacity']

yenergy = ['Demand']
yfossil = ['Gross Load (MWh)']
yaqi = ['aqi']

fe = ['CLIMATE_STATION_NAME','YEAR']
feenergy = ['CLIMATE_STATION_NAME','MONTH']

In [28]:
model_1_panel_results = model_1_panel(totaldataframe, xenergy, y, fe)

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')
/opt/anaconda3/lib/python3.13/site-packages/linearmodels/panel/model.py:1258: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1163
Estimator:                   PanelOLS   R-squared (Between):             -2520.4
No. Observations:              186761   R-squared (Within):               0.1150
Date:                Wed, Mar 11 2026   R-squared (Overall):             -1740.6
Time:                        22:00:44   Log-likelihood                -5.924e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      1116.8
Entities:                           2   P-value                           0.0000
Avg Obs:                    9.338e+04   Distribution:               F(22,186728)
Min Obs:                    9.025e+04
Max Obs:                    9.651e+04   F-statistic (robust):         -9.772e+15
                                        P-value                           1.0000
Time periods:                      10   Distribution:               F(22,186728)
Avg Obs:                    1.868e+04
Min Obs:                       220.00
Max Obs:                    3.378e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -3.1228     0.2279    -13.700     0.0000     -3.5696     -2.6760
DailyAverageWindSpeed                         -0.4788     0.1098    -4.3592     0.0000     -0.6941     -0.2635
DailyDepartureFromNormalAverageTemperature     0.2477     0.0284     8.7292     0.0000      0.1921      0.3033
DailyMaximumDryBulbTemperature                 0.1326     0.0232     5.7107     0.0000      0.0871      0.1782
DailyMinimumDryBulbTemperature                -0.1438     0.0175    -8.2193     0.0000     -0.1780     -0.1095
DailyPeakWindSpeed                            -0.1857     0.0908    -2.0453     0.0408     -0.3637     -0.0077
DailyPrecipitation                             0.0148     0.0056     2.6401     0.0083      0.0038      0.0257
DailySustainedWindSpeed                       -0.1988     0.1325    -1.5006     0.1334     -0.4585      0.0609
DailyPeakWindDirection_sin                     0.5529     0.7125     0.7760     0.4377     -0.8435      1.9493
DailyPeakWindDirection_cos                    -0.4842     0.1269    -3.8157     0.0001     -0.7330     -0.2355
DailySustainedWindDirection_sin               -0.2941     0.6517    -0.4512     0.6518     -1.5713      0.9832
DailySustainedWindDirection_cos               -0.7681     0.2229    -3.4451     0.0006     -1.2050     -0.3311
DailyAverageDewPointTemperature                0.8310     1.8240     0.4556     0.6487     -2.7440      4.4059
DailyAveragePrecipitation                      1.5477     1.0367     1.4929     0.1355     -0.4843      3.5797
DailyAveragePressureChange                     1.9073     0.9758     1.9545     0.0506     -0.0053      3.8198
DailyAverageRelativeHumidity                  -0.5113     0.1341    -3.8121     0.0001     -0.7742     -0.2484
DailyAverageSeaLevelPressure                  -1.9507     0.0464    -42.041     0.0000     -2.0417     -1.8598
DailyAverageStationPressure                    1.5931     0.0401     39.732     0.0000      1.5145      1.6716
DailyAverageWetBulbTemperature                 2.5521     1.5673     1.6284     0.1035     -0.5197      5.6240
DailyAverageWindGustSpeed                     -0.6643     0.2409    -2.7580     0.0058     -1.1364     -0.1922
DailyAverageWindDirection_sin                 -0.2232     2.2798    -0.0979     0.9220     -4.6916      4.2452
DailyAverageWindDirection_cos                 -3.4959     1.6586    -2.1077     0.0351     -6.7467     -0.2450
==============================================================================================================

F-test for Poolability: 523.67
P-value: 0.0000
Distribution: F(10,186728)

Included effects: Entity, Time

In [40]:
from great_tables import GT

from linearmodels.panel.results import PanelEffectsResults

def make_table(results, titles, filename):

    # Detect PanelOLS results object
    if isinstance(results, PanelEffectsResults):

        table = pd.DataFrame({
            "Coefficient": results.params,
            "Std. Error": results.std_errors,
            "t-stat": results.tstats,
            "p-value": results.pvalues
        }).round(4)

        table = table.reset_index()
        table = table.rename(columns={"index": "Variable"})

    # If a dataframe is passed directly
    elif isinstance(results, pd.DataFrame):

        table = results.copy()

        if "Variable" not in table.columns:
            table = table.reset_index()
            table = table.rename(columns={"index": "Variable"})

    else:
        raise ValueError("Unsupported results type")

    # Create formatted table
    gt_table = (
        GT(table)
        .tab_header(
            title="Panel Regression Results",
            subtitle=titles
        )
        .opt_table_font(font="Times New Roman")
    )

    print("Saving table...")

    tablepath = "/Users/griffinberonio/Documents/AAE 724/"

    gt_table.save(f"{tablepath}{filename}.png")

    print("Table saved successfully")

In [39]:
make_table(model_1_panel_results,'AVG PM 2.5 on Climate Variables','model_1_panel.png')
# model_1_panel_results.params

Saving table...
Table saved successfully

In [45]:
model_2_results = model_1_panel(totaldataframe, xenergy, yaqi,fe)

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:149: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')
/opt/anaconda3/lib/python3.13/site-packages/linearmodels/panel/model.py:1258: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    aqi   R-squared:                        0.2170
Estimator:                   PanelOLS   R-squared (Between):             -485.59
No. Observations:              172037   R-squared (Within):               0.2116
Date:                Wed, Mar 11 2026   R-squared (Overall):             -421.18
Time:                        22:13:35   Log-likelihood                -7.092e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      2166.8
Entities:                           2   P-value                           0.0000
Avg Obs:                    8.602e+04   Distribution:               F(22,172004)
Min Obs:                    8.018e+04
Max Obs:                    9.186e+04   F-statistic (robust):           1.08e+15
                                        P-value                           0.0000
Time periods:                      10   Distribution:               F(22,172004)
Avg Obs:                     1.72e+04
Min Obs:                       202.00
Max Obs:                    2.996e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -7.3250     0.9113    -8.0378     0.0000     -9.1112     -5.5389
DailyAverageWindSpeed                         -1.6141     0.2101    -7.6829     0.0000     -2.0259     -1.2023
DailyDepartureFromNormalAverageTemperature     0.9568     0.0296     32.376     0.0000      0.8989      1.0148
DailyMaximumDryBulbTemperature                 0.5133     0.0508     10.098     0.0000      0.4137      0.6129
DailyMinimumDryBulbTemperature                -0.5553     0.0573    -9.6911     0.0000     -0.6676     -0.4430
DailyPeakWindSpeed                            -0.7220     0.3726    -1.9379     0.0526     -1.4523      0.0082
DailyPrecipitation                             0.1163     0.0151     7.6792     0.0000      0.0866      0.1459
DailySustainedWindSpeed                       -0.6422     0.5251    -1.2231     0.2213     -1.6713      0.3869
DailyPeakWindDirection_sin                     1.7127     1.3225     1.2951     0.1953     -0.8793      4.3047
DailyPeakWindDirection_cos                    -2.2106     0.5509    -4.0124     0.0001     -3.2904     -1.1308
DailySustainedWindDirection_sin               -1.1789     1.0677    -1.1042     0.2695     -3.2717      0.9138
DailySustainedWindDirection_cos               -2.6850     0.7777    -3.4524     0.0006     -4.2094     -1.1607
DailyAverageDewPointTemperature                1.5674     3.6749     0.4265     0.6697     -5.6354      8.7702
DailyAveragePrecipitation                      4.9681     3.5154     1.4132     0.1576     -1.9220      11.858
DailyAveragePressureChange                     2.7851     3.1550     0.8828     0.3774     -3.3985      8.9688
DailyAverageRelativeHumidity                  -1.2602     0.0968    -13.023     0.0000     -1.4498     -1.0705
DailyAverageSeaLevelPressure                  -5.2424     0.4381    -11.965     0.0000     -6.1011     -4.3837
DailyAverageStationPressure                    4.5650     0.1703     26.811     0.0000      4.2313      4.8987
DailyAverageWetBulbTemperature                 6.0423     4.4838     1.3476     0.1778     -2.7458      14.830
DailyAverageWindGustSpeed                     -0.8335     0.2119    -3.9333     0.0001     -1.2488     -0.4181
DailyAverageWindDirection_sin                 -2.7113     7.2663    -0.3731     0.7091     -16.953      11.530
DailyAverageWindDirection_cos                 -8.6551     3.9180    -2.2090     0.0272     -16.334     -0.9758
==============================================================================================================

F-test for Poolability: 589.91
P-value: 0.0000
Distribution: F(10,172004)

Included effects: Entity, Time

In [47]:
make_table(model_2_results, 'AQI on Climate Variables', 'model_2_aqi.png')

Saving table...
Table saved successfully

In [49]:
model_3_results = model_3_energy_climate(totaldataframe, xenergy, yenergy, feenergy)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                 Demand   R-squared:                        0.0558
Estimator:                   PanelOLS   R-squared (Between):             -4.9780
No. Observations:              147325   R-squared (Within):               0.0661
Date:                Wed, Mar 11 2026   R-squared (Overall):             -4.8942
Time:                        22:14:34   Log-likelihood                -1.995e+06
Cov. Estimator:             Clustered
                                        F-statistic:                      395.66
Entities:                           2   P-value                           0.0000
Avg Obs:                    7.366e+04   Distribution:               F(22,147290)
Min Obs:                    7.169e+04
Max Obs:                    7.564e+04   F-statistic (robust):         -1.706e+16
                                        P-value                           1.0000
Time periods:                      12   Distribution:               F(22,147290)
Avg Obs:                    1.228e+04
Min Obs:                    1.065e+04
Max Obs:                    1.316e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature             -6.963e+04  5.455e+04    -1.2765     0.2018  -1.765e+05   3.728e+04
DailyAverageWindSpeed                       4.959e+04  3.325e+04     1.4913     0.1359  -1.558e+04   1.148e+05
DailyDepartureFromNormalAverageTemperature -1.089e+04     101.90    -106.88     0.0000  -1.109e+04  -1.069e+04
DailyMaximumDryBulbTemperature                -472.93     91.895    -5.1465     0.0000     -653.05     -292.82
DailyMinimumDryBulbTemperature                 7843.1     1046.3     7.4960     0.0000      5792.3      9893.8
DailyPeakWindSpeed                             1225.2     772.77     1.5855     0.1129     -289.39      2739.8
DailyPrecipitation                            -788.94     189.13    -4.1714     0.0000     -1159.6     -418.25
DailySustainedWindSpeed                        4080.2     1208.5     3.3764     0.0007      1711.6      6448.8
DailyPeakWindDirection_sin                 -1.331e+04     1195.0    -11.134     0.0000  -1.565e+04  -1.096e+04
DailyPeakWindDirection_cos                 -1.832e+04     4681.4    -3.9130     0.0001  -2.749e+04     -9143.1
DailySustainedWindDirection_sin            -1.997e+04     1333.2    -14.983     0.0000  -2.259e+04  -1.736e+04
DailySustainedWindDirection_cos            -1.033e+04     8498.2    -1.2161     0.2240  -2.699e+04      6321.7
DailyAverageDewPointTemperature            -1.425e+05  1.673e+05    -0.8517     0.3944  -4.704e+05   1.854e+05
DailyAveragePrecipitation                   1.252e+04     3023.6     4.1423     0.0000      6598.5   1.845e+04
DailyAveragePressureChange                  1.769e+04  2.918e+04     0.6062     0.5444  -3.951e+04   7.489e+04
DailyAverageRelativeHumidity                   6002.8  2.551e+04     0.2353     0.8140  -4.401e+04   5.601e+04
DailyAverageSeaLevelPressure               -2.823e+04  1.103e+04    -2.5592     0.0105  -4.984e+04     -6608.5
DailyAverageStationPressure                 3.582e+04     4010.2     8.9314     0.0000   2.796e+04   4.368e+04
DailyAverageWetBulbTemperature              2.368e+05   1.13e+05     2.0947     0.0362   1.523e+04   4.583e+05
DailyAverageWindGustSpeed                   -3.98e+04  2.214e+04    -1.7974     0.0723  -8.319e+04      3598.7
DailyAverageWindDirection_sin               1.822e+05  4.114e+04     4.4278     0.0000   1.015e+05   2.628e+05
DailyAverageWindDirection_cos              -3.526e+04  1.385e+04    -2.5458     0.0109   -6.24e+04     -8113.1
==============================================================================================================

F-test for Poolability: 1.511e+04
P-value: 0.0000
Distribution: F(12,147290)

Included effects: Entity, Time

In [50]:
make_table(model_3_results, 'Daily Energy Demand on Climate Variables','model_3_energy.png')

Saving table...
Table saved successfully

In [51]:
model_4_results = model_3_energy_climate(totaldataframe,xenergy, yfossil, feenergy)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:       Gross Load (MWh)   R-squared:                        0.0684
Estimator:                   PanelOLS   R-squared (Between):             -57.501
No. Observations:              187615   R-squared (Within):               0.1562
Date:                Wed, Mar 11 2026   R-squared (Overall):             -51.597
Time:                        22:21:30   Log-likelihood                -2.284e+06
Cov. Estimator:             Clustered
                                        F-statistic:                      626.23
Entities:                           2   P-value                           0.0000
Avg Obs:                    9.381e+04   Distribution:               F(22,187580)
Min Obs:                    9.048e+04
Max Obs:                    9.713e+04   F-statistic (robust):         -9.337e+15
                                        P-value                           1.0000
Time periods:                      12   Distribution:               F(22,187580)
Avg Obs:                    1.563e+04
Min Obs:                    1.375e+04
Max Obs:                    1.678e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature             -1.731e+04     2713.6    -6.3778     0.0000  -2.263e+04  -1.199e+04
DailyAverageWindSpeed                        1.25e+04     5021.8     2.4889     0.0128      2656.1   2.234e+04
DailyDepartureFromNormalAverageTemperature    -2984.0     175.09    -17.043     0.0000     -3327.2     -2640.9
DailyMaximumDryBulbTemperature                 663.94     28.658     23.167     0.0000      607.77      720.11
DailyMinimumDryBulbTemperature                 1530.4     73.218     20.902     0.0000      1386.9      1673.9
DailyPeakWindSpeed                            -7627.4     702.84    -10.852     0.0000     -9004.9     -6249.9
DailyPrecipitation                             59.448     112.14     0.5301     0.5960     -160.34      279.23
DailySustainedWindSpeed                        8443.3     972.59     8.6813     0.0000      6537.1   1.035e+04
DailyPeakWindDirection_sin                    -4800.7     953.60    -5.0344     0.0000     -6669.8     -2931.7
DailyPeakWindDirection_cos                    -2678.0     1075.2    -2.4907     0.0127     -4785.4     -570.65
DailySustainedWindDirection_sin               -1680.7     1800.7    -0.9334     0.3506     -5209.9      1848.6
DailySustainedWindDirection_cos                117.15     947.91     0.1236     0.9016     -1740.7      1975.0
DailyAverageDewPointTemperature            -3.507e+04  2.909e+04    -1.2057     0.2279  -9.209e+04   2.194e+04
DailyAveragePrecipitation                      4034.0     260.61     15.479     0.0000      3523.3      4544.8
DailyAveragePressureChange                     4244.8     399.44     10.627     0.0000      3461.9      5027.7
DailyAverageRelativeHumidity                   951.65     3801.6     0.2503     0.8023     -6499.3      8402.6
DailyAverageSeaLevelPressure                  -5475.9     156.74    -34.936     0.0000     -5783.2     -5168.7
DailyAverageStationPressure                    7022.9     1284.3     5.4684     0.0000      4505.8      9540.0
DailyAverageWetBulbTemperature              5.272e+04   2.57e+04     2.0517     0.0402      2356.0   1.031e+05
DailyAverageWindGustSpeed                     -3281.7     3673.5    -0.8933     0.3717  -1.048e+04      3918.3
DailyAverageWindDirection_sin               1.021e+04     1108.3     9.2091     0.0000      8034.6   1.238e+04
DailyAverageWindDirection_cos               -2.22e+04     3888.1    -5.7092     0.0000  -2.982e+04  -1.458e+04
==============================================================================================================

F-test for Poolability: 5870.8
P-value: 0.0000
Distribution: F(12,187580)

Included effects: Entity, Time

In [52]:
make_table(model_4_results,'Fossil Fuel Generation on Climate Data','model_4_fossil.png')

Saving table...
Table saved successfully

In [54]:
model_5_results = model_3_energy_climate(totaldataframe, xenergyandrenewables,y,feenergy)
make_table(model_5_results, 'AVG PM2.5 on Renewables and Climate', 'model_5_renewables_climate.png')

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1245
Estimator:                   PanelOLS   R-squared (Between):             -2769.3
No. Observations:              186761   R-squared (Within):               0.1070
Date:                Wed, Mar 11 2026   R-squared (Overall):             -1912.5
Time:                        22:27:09   Log-likelihood                -5.898e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      1106.3
Entities:                           2   P-value                           0.0000
Avg Obs:                    9.338e+04   Distribution:               F(24,186724)
Min Obs:                    9.025e+04
Max Obs:                    9.651e+04   F-statistic (robust):         -8.493e+15
                                        P-value                           1.0000
Time periods:                      12   Distribution:               F(24,186724)
Avg Obs:                    1.556e+04
Min Obs:                    1.367e+04
Max Obs:                    1.673e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -2.7146     0.3320    -8.1759     0.0000     -3.3654     -2.0639
DailyAverageWindSpeed                         -0.1833     0.0471    -3.8874     0.0001     -0.2757     -0.0909
DailyDepartureFromNormalAverageTemperature     0.1790     0.0374     4.7835     0.0000      0.1056      0.2523
DailyMaximumDryBulbTemperature                 0.2047     0.0281     7.2713     0.0000      0.1495      0.2598
DailyMinimumDryBulbTemperature                -0.1698     0.0060    -28.271     0.0000     -0.1815     -0.1580
DailyPeakWindSpeed                            -0.2114     0.0779    -2.7133     0.0067     -0.3640     -0.0587
DailyPrecipitation                             0.0201     0.0053     3.7759     0.0002      0.0097      0.0305
DailySustainedWindSpeed                       -0.1385     0.1135    -1.2205     0.2223     -0.3610      0.0839
DailyPeakWindDirection_sin                     0.8251     0.5450     1.5140     0.1300     -0.2431      1.8932
DailyPeakWindDirection_cos                    -0.5676     0.2613    -2.1719     0.0299     -1.0798     -0.0554
DailySustainedWindDirection_sin               -0.2524     0.4984    -0.5064     0.6126     -1.2293      0.7245
DailySustainedWindDirection_cos               -0.7307     0.3136    -2.3305     0.0198     -1.3453     -0.1162
DailyAverageDewPointTemperature               -0.1312     2.2278    -0.0589     0.9530     -4.4977      4.2352
DailyAveragePrecipitation                      0.7073     0.5735     1.2334     0.2174     -0.4167      1.8312
DailyAveragePressureChange                     1.9025     0.8121     2.3428     0.0191      0.3108      3.4942
DailyAverageRelativeHumidity                  -0.3298     0.2216    -1.4886     0.1366     -0.7641      0.1044
DailyAverageSeaLevelPressure                  -1.7286     0.1445    -11.962     0.0000     -2.0118     -1.4454
DailyAverageStationPressure                    1.3240     0.2324     5.6979     0.0000      0.8686      1.7795
DailyAverageWetBulbTemperature                 3.1441     1.8890     1.6644     0.0960     -0.5583      6.8465
DailyAverageWindGustSpeed                     -0.6943     0.2884    -2.4075     0.0161     -1.2595     -0.1291
DailyAverageWindDirection_sin                  0.1676     1.9221     0.0872     0.9305     -3.5997      3.9349
DailyAverageWindDirection_cos                 -3.0048     1.7695    -1.6981     0.0895     -6.4729      0.4633
Number                                         0.0014  3.383e-05     42.121     0.0000      0.0014      0.0015
Capacity                                      -0.2021     0.0666    -3.0337     0.0024     -0.3327     -0.0715
==============================================================================================================

F-test for Poolability: 896.68
P-value: 0.0000
Distribution: F(12,186724)

Included effects: Entity, Time
Saving table...
Table saved successfully

In [55]:
model_6_results = model_3_energy_climate(totaldataframe,xenergyandrenewables,yaqi,fe)
make_table(model_6_results, 'AQI on Renewables and Climate Variables', 'model_6_aqi_renewables.png')

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    aqi   R-squared:                        0.2170
Estimator:                   PanelOLS   R-squared (Between):             -486.04
No. Observations:              172037   R-squared (Within):               0.2115
Date:                Wed, Mar 11 2026   R-squared (Overall):             -421.58
Time:                        22:35:08   Log-likelihood                -7.092e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      1986.4
Entities:                           2   P-value                           0.0000
Avg Obs:                    8.602e+04   Distribution:               F(24,172002)
Min Obs:                    8.018e+04
Max Obs:                    9.186e+04   F-statistic (robust):          3.054e+16
                                        P-value                           0.0000
Time periods:                      10   Distribution:               F(24,172002)
Avg Obs:                     1.72e+04
Min Obs:                       202.00
Max Obs:                    2.996e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -7.3225     0.8664    -8.4513     0.0000     -9.0207     -5.6243
DailyAverageWindSpeed                         -1.6115     0.2139    -7.5350     0.0000     -2.0306     -1.1923
DailyDepartureFromNormalAverageTemperature     0.9573     0.0290     33.004     0.0000      0.9004      1.0141
DailyMaximumDryBulbTemperature                 0.5136     0.0510     10.077     0.0000      0.4137      0.6134
DailyMinimumDryBulbTemperature                -0.5558     0.0577    -9.6259     0.0000     -0.6690     -0.4427
DailyPeakWindSpeed                            -0.7209     0.3698    -1.9494     0.0512     -1.4457      0.0039
DailyPrecipitation                             0.1162     0.0150     7.7283     0.0000      0.0868      0.1457
DailySustainedWindSpeed                       -0.6444     0.5213    -1.2361     0.2164     -1.6661      0.3774
DailyPeakWindDirection_sin                     1.7154     1.3169     1.3026     0.1927     -0.8658      4.2965
DailyPeakWindDirection_cos                    -2.2118     0.5557    -3.9800     0.0001     -3.3010     -1.1226
DailySustainedWindDirection_sin               -1.1820     1.0632    -1.1118     0.2662     -3.2658      0.9017
DailySustainedWindDirection_cos               -2.6877     0.7820    -3.4371     0.0006     -4.2203     -1.1550
DailyAverageDewPointTemperature                1.5807     3.9021     0.4051     0.6854     -6.0673      9.2288
DailyAveragePrecipitation                      4.9765     3.3730     1.4754     0.1401     -1.6345      11.587
DailyAveragePressureChange                     2.7623     2.8811     0.9588     0.3377     -2.8846      8.4092
DailyAverageRelativeHumidity                  -1.2625     0.1465    -8.6174     0.0000     -1.5497     -0.9754
DailyAverageSeaLevelPressure                  -5.2480     0.3113    -16.857     0.0000     -5.8582     -4.6378
DailyAverageStationPressure                    4.5704     0.0504     90.645     0.0000      4.4716      4.6692
DailyAverageWetBulbTemperature                 6.0264     4.6632     1.2923     0.1962     -3.1135      15.166
DailyAverageWindGustSpeed                     -0.8323     0.1963    -4.2407     0.0000     -1.2170     -0.4476
DailyAverageWindDirection_sin                 -2.7300     7.0413    -0.3877     0.6982     -16.531      11.071
DailyAverageWindDirection_cos                 -8.6461     3.9657    -2.1802     0.0292     -16.419     -0.8735
Number                                        -0.0036     0.0021    -1.6999     0.0892     -0.0077      0.0005
Capacity                                       0.3190     0.3150     1.0128     0.3112     -0.2984      0.9365
==============================================================================================================

F-test for Poolability: 586.67
P-value: 0.0000
Distribution: F(10,172002)

Included effects: Entity, Time
Saving table...
Table saved successfully