In [1]:
import pandas as pd
import geopandas as gpd 
import requests 
import json
from datetime import datetime
from io import StringIO
import csv
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from shapely import wkt
from scipy.spatial.distance import cdist

import pandas as pd
import geopandas as gpd 
import requests 
import json
from datetime import datetime
from io import StringIO
import csv
import time
import os
import airqualityandclimateAPI
import statsmodels.api as sm

from statsmodels.stats.outliers_influence \
     import variance_inflation_factor as VIF
from statsmodels.stats.anova import anova_lm

from ISLP import load_data
from ISLP.models import (ModelSpec as MS,
                         summarize,
                         poly)
from linearmodels import PanelOLS

In [2]:
import sklearn.model_selection as skm
import sklearn.linear_model as skl
from sklearn.preprocessing import StandardScaler
from ISLP import load_data
from ISLP.models import (ModelSpec as MS, summarize)
from functools import partial
from sklearn.pipeline import Pipeline
# from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression
from ISLP.models import \
     (Stepwise,
      sklearn_selected,
      sklearn_selection_path)

In [3]:
from Analysis import *

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:27: DtypeWarning: Columns (9,11,12,13,14,15,18,23,28,36,38,40,55,56,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,106) have mixed types. Specify dtype option on import or set low_memory=False.
  climatedata = pd.read_csv(climatedatapath)
/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:31: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  airqualitydata = pd.read_csv(airqualitydatapath)
/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:50: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  totaldf = pd.read_csv(totaldatapath)

In [4]:
totaldataframe = totaldata()

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:68: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  totaldf = pd.read_csv(totaldatapath)

In [5]:
# totaldata['YEAR'] = pd.to_datetime(totaldata['DATE']).dt.year
station_year_check = totaldataframe.groupby('CLIMATE_STATION_NAME')['YEAR'].nunique()
print(station_year_check)

CLIMATE_STATION_NAME
CHICAGO MIDWAY AIRPORT, IL US       10
CHICAGO PALWAUKEE AIRPORT, IL US    10
Name: YEAR, dtype: int64

# Model 1

In [6]:
xclimate = ['DailyAverageDryBulbTemperature', 'DailyAverageWindSpeed','DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindSpeed',
       'DailyPrecipitation','DailySustainedWindSpeed', 'DailySustainedWindDirection_sin', 'DailySustainedWindDirection_cos',
       'DailyAveragePrecipitation', 'DailyAveragePressureChange',
       'DailyAverageRelativeHumidity',]

y = ['arithmetic_mean']

fe = ['DATE','CLIMATE_STATION_NAME']

model_1_results = model_1(totaldataframe, xclimate, y, fe)
model_1_results

# table = pd.DataFrame({
#     "Coefficient": model_1_results.params,
#     "Std. Error": model_1_results.std_errors,
#     "t-stat": model_1_results.tstats,
#     "p-value": model_1_results.pvalues
# })

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:131: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DATE'] = pd.to_datetime(df['DATE'])
/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:135: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['YEAR'] = pd.to_numeric(df['DATE'].dt.year)

                                                index    coef  std err  \
0                                               const -1.9172   10.097
1                      DailyAverageDryBulbTemperature  0.3196    0.142
2                               DailyAverageWindSpeed  0.5199    0.387
3                      DailyMaximumDryBulbTemperature  0.1575    0.023
4                      DailyMinimumDryBulbTemperature -0.1280    0.021
5                                  DailyPeakWindSpeed -0.2002    0.153
6                                  DailyPrecipitation  0.0199    0.010
7                             DailySustainedWindSpeed -0.1222    0.239
8                     DailySustainedWindDirection_sin  0.1171    0.052
9                     DailySustainedWindDirection_cos -1.7295    0.034
10                          DailyAveragePrecipitation -0.5111    0.756
11                         DailyAveragePressureChange  0.8020    0.097
12                       DailyAverageRelativeHumidity  0.1069    0.099
13  CLIMATE_STATION_NAME_CHICAGO PALWAUKEE AIRPORT... -0.6283    0.105
14                                          YEAR_2017  0.1850    0.049
15                                          YEAR_2018  0.7514    0.048
16                                          YEAR_2019  0.3373    0.023
17                                          YEAR_2020  0.0535    0.590
18                                          YEAR_2021  0.5676    0.172
19                                          YEAR_2022 -0.3866    0.420
20                                          YEAR_2023  2.5496    0.103
21                                          YEAR_2024 -0.6587    0.059
22                                          YEAR_2025 -2.5679    0.342

         z  P>|z|
0   -0.190  0.849
1    2.246  0.025
2    1.343  0.179
3    6.993  0.000
4   -5.976  0.000
5   -1.306  0.192
6    1.931  0.053
7   -0.511  0.610
8    2.244  0.025
9  -51.456  0.000
10  -0.676  0.499
11   8.256  0.000
12   1.080  0.280
13  -6.007  0.000
14   3.811  0.000
15  15.555  0.000
16  14.723  0.000
17   0.091  0.928
18   3.307  0.001
19  -0.920  0.357
20  24.701  0.000
21 -11.234  0.000
22  -7.511  0.000

/opt/anaconda3/lib/python3.13/site-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 22, but rank is 1
  warnings.warn('covariance of constraints does not have full '

,index,coef,std err,z,P>|z|
0,const,-1.9172,10.097,-0.190,0.849
1,DailyAverageDryBulbTemperature,0.3196,0.142,2.246,0.025
2,DailyAverageWindSpeed,0.5199,0.387,1.343,0.179
3,DailyMaximumDryBulbTemperature,0.1575,0.023,6.993,0.000
4,DailyMinimumDryBulbTemperature,-0.1280,0.021,-5.976,0.000
5,DailyPeakWindSpeed,-0.2002,0.153,-1.306,0.192
6,DailyPrecipitation,0.0199,0.010,1.931,0.053
7,DailySustainedWindSpeed,-0.1222,0.239,-0.511,0.610
8,DailySustainedWindDirection_sin,0.1171,0.052,2.244,0.025
9,DailySustainedWindDirection_cos,-1.7295,0.034,-51.456,0.000
10,DailyAveragePrecipitation,-0.5111,0.756,-0.676,0.499
11,DailyAveragePressureChange,0.8020,0.097,8.256,0.000
12,DailyAverageRelativeHumidity,0.1069,0.099,1.080,0.280
13,CLIMATE_STATION_NAME_CHICAGO PALWAUKEE AIRPORT...,-0.6283,0.105,-6.007,0.000
14,YEAR_2017,0.1850,0.049,3.811,0.000
15,YEAR_2018,0.7514,0.048,15.555,0.000
16,YEAR_2019,0.3373,0.023,14.723,0.000
17,YEAR_2020,0.0535,0.590,0.091,0.928
18,YEAR_2021,0.5676,0.172,3.307,0.001
19,YEAR_2022,-0.3866,0.420,-0.920,0.357
20,YEAR_2023,2.5496,0.103,24.701,0.000
21,YEAR_2024,-0.6587,0.059,-11.234,0.000
22,YEAR_2025,-2.5679,0.342,-7.511,0.000

In [7]:
model_1_table = model_1_results
model_1_table = model_1_table.rename(columns={'index':'Variable'})
model_1_table.reset_index(inplace=True)
model_1_table.head()

   index                        Variable    coef  std err      z  P>|z|
0      0                           const -1.9172   10.097 -0.190  0.849
1      1  DailyAverageDryBulbTemperature  0.3196    0.142  2.246  0.025
2      2           DailyAverageWindSpeed  0.5199    0.387  1.343  0.179
3      3  DailyMaximumDryBulbTemperature  0.1575    0.023  6.993  0.000
4      4  DailyMinimumDryBulbTemperature -0.1280    0.021 -5.976  0.000

In [8]:
xenergy= ['DailyAverageDryBulbTemperature', 'DailyAverageWindSpeed',
        'DailyDepartureFromNormalAverageTemperature',
        'DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindSpeed',
       'DailyPrecipitation',
       'DailySustainedWindSpeed',
       'DailyPeakWindDirection_sin', 'DailyPeakWindDirection_cos',
       'DailySustainedWindDirection_sin', 'DailySustainedWindDirection_cos',
       'DailyAverageDewPointTemperature',
       'DailyAveragePrecipitation', 'DailyAveragePressureChange',
       'DailyAverageRelativeHumidity', 'DailyAverageSeaLevelPressure',
       'DailyAverageStationPressure', 'DailyAverageWetBulbTemperature',
       'DailyAverageWindGustSpeed', 'DailyAverageWindDirection_sin',
       'DailyAverageWindDirection_cos']

xenergyandrenewables = xenergy + ['Number', 'Capacity']

yenergy = ['Demand']
yfossil = ['Gross Load (MWh)']
yaqi = ['aqi']

fe = ['CLIMATE_STATION_NAME','YEAR']
feenergy = ['CLIMATE_STATION_NAME','MONTH']

In [9]:
model_1_panel_results = model_1_panel(totaldataframe, xenergy, y, fe)

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:185: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')
/opt/anaconda3/lib/python3.13/site-packages/linearmodels/panel/model.py:1258: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1127
Estimator:                   PanelOLS   R-squared (Between):             -3591.9
No. Observations:               72987   R-squared (Within):               0.1113
Date:                Thu, Mar 19 2026   R-squared (Overall):             -2469.1
Time:                        11:12:35   Log-likelihood                -2.328e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      421.20
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(22,72954)
Min Obs:                    3.575e+04
Max Obs:                    3.724e+04   F-statistic (robust):         -1.002e+16
                                        P-value                           1.0000
Time periods:                      10   Distribution:                F(22,72954)
Avg Obs:                       7298.7
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -2.6659     0.2377    -11.217     0.0000     -3.1317     -2.2001
DailyAverageWindSpeed                         -0.3517     0.1297    -2.7118     0.0067     -0.6059     -0.0975
DailyDepartureFromNormalAverageTemperature     0.2211     0.0285     7.7493     0.0000      0.1652      0.2770
DailyMaximumDryBulbTemperature                 0.1464     0.0180     8.1252     0.0000      0.1111      0.1817
DailyMinimumDryBulbTemperature                -0.1537     0.0118    -12.987     0.0000     -0.1769     -0.1305
DailyPeakWindSpeed                            -0.2273     0.0957    -2.3742     0.0176     -0.4149     -0.0396
DailyPrecipitation                             0.0159     0.0049     3.2823     0.0010      0.0064      0.0255
DailySustainedWindSpeed                       -0.1263     0.1391    -0.9078     0.3640     -0.3990      0.1464
DailyPeakWindDirection_sin                     0.5501     0.6646     0.8278     0.4078     -0.7525      1.8527
DailyPeakWindDirection_cos                    -0.5858     0.1381    -4.2421     0.0000     -0.8565     -0.3152
DailySustainedWindDirection_sin               -0.2632     0.6012    -0.4378     0.6615     -1.4416      0.9152
DailySustainedWindDirection_cos               -0.7840     0.2402    -3.2637     0.0011     -1.2549     -0.3132
DailyAverageDewPointTemperature               -0.0938     1.6862    -0.0556     0.9556     -3.3987      3.2111
DailyAveragePrecipitation                      1.3160     0.6484     2.0295     0.0424      0.0451      2.5869
DailyAveragePressureChange                     2.0990     1.1225     1.8700     0.0615     -0.1010      4.2991
DailyAverageRelativeHumidity                  -0.3293     0.1340    -2.4581     0.0140     -0.5918     -0.0667
DailyAverageSeaLevelPressure                  -2.2358     0.0280    -79.934     0.0000     -2.2906     -2.1810
DailyAverageStationPressure                    1.7732     0.0676     26.234     0.0000      1.6407      1.9057
DailyAverageWetBulbTemperature                 3.0005     1.4190     2.1145     0.0345      0.2192      5.7819
DailyAverageWindGustSpeed                     -0.7318     0.2499    -2.9280     0.0034     -1.2217     -0.2419
DailyAverageWindDirection_sin                 -0.8361     2.4253    -0.3447     0.7303     -5.5898      3.9176
DailyAverageWindDirection_cos                 -3.5998     1.7381    -2.0712     0.0383     -7.0064     -0.1932
==============================================================================================================

F-test for Poolability: 205.49
P-value: 0.0000
Distribution: F(10,72954)

Included effects: Entity, Time

In [10]:
from great_tables import GT

from linearmodels.panel.results import PanelEffectsResults

def make_table(results, titles, filename):

    # Detect PanelOLS results object
    if isinstance(results, PanelEffectsResults):

        table = pd.DataFrame({
            "Coefficient": results.params,
            "Std. Error": results.std_errors,
            "t-stat": results.tstats,
            "p-value": results.pvalues
        }).round(4)

        table = table.reset_index()
        table = table.rename(columns={"index": "Variable"})

    # If a dataframe is passed directly
    elif isinstance(results, pd.DataFrame):

        table = results.copy()

        if "Variable" not in table.columns:
            table = table.reset_index()
            table = table.rename(columns={"index": "Variable"})

    else:
        raise ValueError("Unsupported results type")

    # Create formatted table
    gt_table = (
        GT(table)
        .tab_header(
            title="Panel Regression Results",
            subtitle=titles
        )
        .opt_table_font(font="Times New Roman")
    )

    print("Saving table...")

    tablepath = "/Users/griffinberonio/Documents/AAE 724/"

    gt_table.save(f"{tablepath}{filename}.png")

    print("Table saved successfully")

In [11]:
make_table(model_1_panel_results,'AVG PM 2.5 on Climate Variables','model_1_panel.png')
# model_1_panel_results.params

Saving table...
Table saved successfully

In [12]:
model_2_results = model_1_panel(totaldataframe, xenergy, yaqi,fe)

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:185: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')
/opt/anaconda3/lib/python3.13/site-packages/linearmodels/panel/model.py:1258: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(dependent, exog, weights=weights, check_rank=check_rank)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    aqi   R-squared:                        0.2051
Estimator:                   PanelOLS   R-squared (Between):             -576.76
No. Observations:               72987   R-squared (Within):               0.2018
Date:                Thu, Mar 19 2026   R-squared (Overall):             -501.55
Time:                        11:12:38   Log-likelihood                 -3.02e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      855.57
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(22,72954)
Min Obs:                    3.575e+04
Max Obs:                    3.724e+04   F-statistic (robust):          7.597e+15
                                        P-value                           0.0000
Time periods:                      10   Distribution:                F(22,72954)
Avg Obs:                       7298.7
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -7.0953     0.7881    -9.0030     0.0000     -8.6399     -5.5506
DailyAverageWindSpeed                         -1.2536     0.0806    -15.563     0.0000     -1.4115     -1.0958
DailyDepartureFromNormalAverageTemperature     0.8707     0.0292     29.816     0.0000      0.8135      0.9280
DailyMaximumDryBulbTemperature                 0.5709     0.0360     15.854     0.0000      0.5004      0.6415
DailyMinimumDryBulbTemperature                -0.6050     0.0395    -15.318     0.0000     -0.6824     -0.5276
DailyPeakWindSpeed                            -0.8707     0.3890    -2.2381     0.0252     -1.6333     -0.1082
DailyPrecipitation                             0.1140     0.0129     8.8153     0.0000      0.0887      0.1394
DailySustainedWindSpeed                       -0.3684     0.5585    -0.6596     0.5095     -1.4631      0.7263
DailyPeakWindDirection_sin                     1.6236     1.2361     1.3135     0.1890     -0.7992      4.0464
DailyPeakWindDirection_cos                    -2.1657     0.5449    -3.9745     0.0001     -3.2337     -1.0977
DailySustainedWindDirection_sin               -1.0221     0.9776    -1.0456     0.2958     -2.9381      0.8939
DailySustainedWindDirection_cos               -2.8565     0.7680    -3.7196     0.0002     -4.3616     -1.3513
DailyAverageDewPointTemperature                1.0777     4.4536     0.2420     0.8088     -7.6514      9.8068
DailyAveragePrecipitation                      3.7450     1.8177     2.0602     0.0394      0.1822      7.3077
DailyAveragePressureChange                     2.9638     3.5870     0.8263     0.4087     -4.0667      9.9943
DailyAverageRelativeHumidity                  -1.0744     0.2588    -4.1517     0.0000     -1.5816     -0.5672
DailyAverageSeaLevelPressure                  -5.6270     0.2225    -25.290     0.0000     -6.0631     -5.1909
DailyAverageStationPressure                    4.8445     0.0788     61.442     0.0000      4.6899      4.9990
DailyAverageWetBulbTemperature                 6.3635     5.1572     1.2339     0.2172     -3.7445      16.472
DailyAverageWindGustSpeed                     -0.7419     0.3334    -2.2250     0.0261     -1.3954     -0.0884
DailyAverageWindDirection_sin                 -3.8826     7.4201    -0.5233     0.6008     -18.426      10.661
DailyAverageWindDirection_cos                 -8.3238     4.3740    -1.9030     0.0570     -16.897      0.2493
==============================================================================================================

F-test for Poolability: 194.76
P-value: 0.0000
Distribution: F(10,72954)

Included effects: Entity, Time

In [13]:
make_table(model_2_results, 'AQI on Climate Variables', 'model_2_aqi.png')

Saving table...
Table saved successfully

In [14]:
energydata = totaldata(include_demand=True)
model_3_results = model_3_energy_climate(energydata, xenergy, yenergy, feenergy)

/Users/griffinberonio/Documents/AAE 724/AAE-724-Repo/Analysis.py:68: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  totaldf = pd.read_csv(totaldatapath)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                 Demand   R-squared:                        0.0516
Estimator:                   PanelOLS   R-squared (Between):             -6.0674
No. Observations:               55495   R-squared (Within):               0.0665
Date:                Thu, Mar 19 2026   R-squared (Overall):             -5.9606
Time:                        11:12:40   Log-likelihood                -7.523e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      137.04
Entities:                           2   P-value                           0.0000
Avg Obs:                    2.775e+04   Distribution:                F(22,55460)
Min Obs:                    2.724e+04
Max Obs:                    2.825e+04   F-statistic (robust):          2.912e+16
                                        P-value                           0.0000
Time periods:                      12   Distribution:                F(22,55460)
Avg Obs:                       4624.6
Min Obs:                       3986.0
Max Obs:                       5665.0

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature             -1.084e+05  5.096e+04    -2.1270     0.0334  -2.083e+05     -8508.2
DailyAverageWindSpeed                       4.576e+04  3.403e+04     1.3448     0.1787  -2.093e+04   1.125e+05
DailyDepartureFromNormalAverageTemperature    -8950.7     410.14    -21.823     0.0000     -9754.6     -8146.8
DailyMaximumDryBulbTemperature                -1222.2     70.039    -17.450     0.0000     -1359.5     -1084.9
DailyMinimumDryBulbTemperature                 6176.9     1184.2     5.2160     0.0000      3855.8      8498.0
DailyPeakWindSpeed                            -750.41     2130.8    -0.3522     0.7247     -4926.7      3425.9
DailyPrecipitation                            -591.04     307.06    -1.9248     0.0543     -1192.9      10.799
DailySustainedWindSpeed                        5761.9     3098.1     1.8598     0.0629     -310.48   1.183e+04
DailyPeakWindDirection_sin                 -2.195e+04     108.43    -202.42     0.0000  -2.216e+04  -2.174e+04
DailyPeakWindDirection_cos                   -1.6e+04     5950.3    -2.6895     0.0072  -2.767e+04     -4340.5
DailySustainedWindDirection_sin            -1.346e+04     53.428    -251.88     0.0000  -1.356e+04  -1.335e+04
DailySustainedWindDirection_cos               -9484.8  1.008e+04    -0.9411     0.3466  -2.924e+04   1.027e+04
DailyAverageDewPointTemperature            -1.175e+05  1.329e+05    -0.8837     0.3768   -3.78e+05    1.43e+05
DailyAveragePrecipitation                   2.198e+04  1.655e+04     1.3285     0.1840  -1.045e+04   5.442e+04
DailyAveragePressureChange                  1.355e+04  3.349e+04     0.4045     0.6858  -5.209e+04   7.919e+04
DailyAverageRelativeHumidity                  -457.74  2.093e+04    -0.0219     0.9825  -4.148e+04   4.056e+04
DailyAverageSeaLevelPressure               -2.375e+04     6169.0    -3.8505     0.0001  -3.584e+04  -1.166e+04
DailyAverageStationPressure                 3.243e+04     2149.6     15.085     0.0000   2.821e+04   3.664e+04
DailyAverageWetBulbTemperature              2.513e+05  8.139e+04     3.0880     0.0020   9.181e+04   4.109e+05
DailyAverageWindGustSpeed                  -3.758e+04  2.209e+04    -1.7012     0.0889  -8.087e+04      5716.6
DailyAverageWindDirection_sin               1.723e+05  3.944e+04     4.3683     0.0000   9.499e+04   2.496e+05
DailyAverageWindDirection_cos              -5.733e+04  1.738e+04    -3.2981     0.0010  -9.139e+04  -2.326e+04
==============================================================================================================

F-test for Poolability: 5760.8
P-value: 0.0000
Distribution: F(12,55460)

Included effects: Entity, Time

In [15]:
make_table(model_3_results, 'Daily Energy Demand on Climate Variables','model_3_energy.png')

Saving table...
Table saved successfully

In [16]:
model_4_results = model_3_energy_climate(totaldataframe,xenergy, yfossil, feenergy)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:       Gross Load (MWh)   R-squared:                        0.0757
Estimator:                   PanelOLS   R-squared (Between):             -62.477
No. Observations:               72987   R-squared (Within):               0.1698
Date:                Thu, Mar 19 2026   R-squared (Overall):             -56.125
Time:                        11:12:41   Log-likelihood                -8.897e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      271.61
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(22,72952)
Min Obs:                    3.575e+04
Max Obs:                    3.724e+04   F-statistic (robust):          5.118e+15
                                        P-value                           0.0000
Time periods:                      12   Distribution:                F(22,72952)
Avg Obs:                       6082.2
Min Obs:                       5305.0
Max Obs:                       7125.0

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature              -2.74e+04     2097.5    -13.062     0.0000  -3.151e+04  -2.329e+04
DailyAverageWindSpeed                       1.285e+04     5969.3     2.1535     0.0313      1155.2   2.455e+04
DailyDepartureFromNormalAverageTemperature    -2841.3     155.52    -18.270     0.0000     -3146.1     -2536.5
DailyMaximumDryBulbTemperature                 581.95     19.718     29.513     0.0000      543.30      620.59
DailyMinimumDryBulbTemperature                 1388.7     107.71     12.893     0.0000      1177.6      1599.8
DailyPeakWindSpeed                            -8422.9     755.78    -11.145     0.0000     -9904.2     -6941.6
DailyPrecipitation                             120.48     147.63     0.8161     0.4144     -168.87      409.83
DailySustainedWindSpeed                        9470.6     1061.5     8.9219     0.0000      7390.0   1.155e+04
DailyPeakWindDirection_sin                    -5739.2     1203.4    -4.7692     0.0000     -8097.9     -3380.6
DailyPeakWindDirection_cos                    -2784.8     1294.2    -2.1516     0.0314     -5321.5     -248.04
DailySustainedWindDirection_sin               -1038.9     2249.7    -0.4618     0.6442     -5448.2      3370.4
DailySustainedWindDirection_cos                279.77     923.17     0.3031     0.7618     -1529.6      2089.2
DailyAverageDewPointTemperature            -3.259e+04  2.439e+04    -1.3364     0.1814  -8.039e+04   1.521e+04
DailyAveragePrecipitation                      3274.1     724.45     4.5194     0.0000      1854.2      4694.0
DailyAveragePressureChange                     83.697     764.57     0.1095     0.9128     -1414.9      1582.2
DailyAverageRelativeHumidity                  -227.42     3163.0    -0.0719     0.9427     -6426.9      5972.1
DailyAverageSeaLevelPressure                  -4606.0     736.59    -6.2532     0.0000     -6049.7     -3162.3
DailyAverageStationPressure                    6334.0     1754.6     3.6100     0.0003      2895.0      9773.0
DailyAverageWetBulbTemperature              5.986e+04  2.137e+04     2.8013     0.0051   1.798e+04   1.017e+05
DailyAverageWindGustSpeed                     -2217.0     4036.2    -0.5493     0.5828  -1.013e+04      5693.9
DailyAverageWindDirection_sin                  8441.8     1495.3     5.6457     0.0000      5511.1   1.137e+04
DailyAverageWindDirection_cos              -2.595e+04     4178.8    -6.2099     0.0000  -3.414e+04  -1.776e+04
==============================================================================================================

F-test for Poolability: 2116.7
P-value: 0.0000
Distribution: F(12,72952)

Included effects: Entity, Time

In [17]:
make_table(model_4_results,'Fossil Fuel Generation on Climate Data','model_4_fossil.png')

Saving table...
Table saved successfully

In [18]:
model_5_results = model_3_energy_climate(totaldataframe, xenergyandrenewables,y,feenergy)
make_table(model_5_results, 'AVG PM2.5 on Renewables and Climate', 'model_5_renewables_climate.png')

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:        arithmetic_mean   R-squared:                        0.1221
Estimator:                   PanelOLS   R-squared (Between):             -3596.6
No. Observations:               72987   R-squared (Within):               0.1059
Date:                Thu, Mar 19 2026   R-squared (Overall):             -2472.4
Time:                        11:12:42   Log-likelihood                -2.318e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      422.71
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(24,72950)
Min Obs:                    3.575e+04
Max Obs:                    3.724e+04   F-statistic (robust):         -4.843e+15
                                        P-value                           1.0000
Time periods:                      12   Distribution:                F(24,72950)
Avg Obs:                       6082.2
Min Obs:                       5305.0
Max Obs:                       7125.0

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -2.4366     0.3128    -7.7909     0.0000     -3.0496     -1.8236
DailyAverageWindSpeed                         -0.1902     0.0081    -23.628     0.0000     -0.2060     -0.1744
DailyDepartureFromNormalAverageTemperature     0.1742     0.0384     4.5393     0.0000      0.0990      0.2494
DailyMaximumDryBulbTemperature                 0.2064     0.0255     8.1089     0.0000      0.1565      0.2563
DailyMinimumDryBulbTemperature                -0.1783     0.0012    -148.23     0.0000     -0.1806     -0.1759
DailyPeakWindSpeed                            -0.2243     0.0906    -2.4747     0.0133     -0.4019     -0.0466
DailyPrecipitation                             0.0204     0.0065     3.1156     0.0018      0.0076      0.0332
DailySustainedWindSpeed                       -0.1050     0.1374    -0.7639     0.4450     -0.3744      0.1644
DailyPeakWindDirection_sin                     0.7946     0.4855     1.6365     0.1017     -0.1571      1.7462
DailyPeakWindDirection_cos                    -0.5954     0.2434    -2.4464     0.0144     -1.0724     -0.1184
DailySustainedWindDirection_sin               -0.2034     0.4623    -0.4399     0.6600     -1.1095      0.7028
DailySustainedWindDirection_cos               -0.8040     0.2992    -2.6873     0.0072     -1.3904     -0.2176
DailyAverageDewPointTemperature               -0.5226     2.3975    -0.2180     0.8274     -5.2216      4.1764
DailyAveragePrecipitation                      0.4048     0.2356     1.7183     0.0857     -0.0569      0.8665
DailyAveragePressureChange                     1.8761     0.9956     1.8844     0.0595     -0.0753      3.8274
DailyAverageRelativeHumidity                  -0.2461     0.2456    -1.0019     0.3164     -0.7275      0.2353
DailyAverageSeaLevelPressure                  -1.8919     0.0931    -20.311     0.0000     -2.0744     -1.7093
DailyAverageStationPressure                    1.4104     0.2140     6.5920     0.0000      0.9911      1.8298
DailyAverageWetBulbTemperature                 3.2546     2.0746     1.5688     0.1167     -0.8116      7.3209
DailyAverageWindGustSpeed                     -0.6775     0.3021    -2.2428     0.0249     -1.2696     -0.0854
DailyAverageWindDirection_sin                 -0.6525     1.9910    -0.3277     0.7431     -4.5549      3.2499
DailyAverageWindDirection_cos                 -2.6766     1.9507    -1.3721     0.1700     -6.5000      1.1467
Number                                         0.0047     0.0004     10.768     0.0000      0.0039      0.0056
Capacity                                      -0.4366     0.0958    -4.5558     0.0000     -0.6244     -0.2487
==============================================================================================================

F-test for Poolability: 336.22
P-value: 0.0000
Distribution: F(12,72950)

Included effects: Entity, Time
Saving table...
Table saved successfully

In [19]:
model_6_results = model_3_energy_climate(totaldataframe,xenergyandrenewables,yaqi,fe)
make_table(model_6_results, 'AQI on Renewables and Climate Variables', 'model_6_aqi_renewables.png')

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                    aqi   R-squared:                        0.2051
Estimator:                   PanelOLS   R-squared (Between):             -571.00
No. Observations:               72987   R-squared (Within):               0.2021
Date:                Thu, Mar 19 2026   R-squared (Overall):             -496.54
Time:                        11:12:44   Log-likelihood                 -3.02e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      784.48
Entities:                           2   P-value                           0.0000
Avg Obs:                    3.649e+04   Distribution:                F(24,72952)
Min Obs:                    3.575e+04
Max Obs:                    3.724e+04   F-statistic (robust):         -2.069e+17
                                        P-value                           1.0000
Time periods:                      10   Distribution:                F(24,72952)
Avg Obs:                       7298.7
Min Obs:                       96.000
Max Obs:                    1.184e+04

                                             Parameter Estimates
==============================================================================================================
                                            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------------------------
DailyAverageDryBulbTemperature                -7.0887     0.7711    -9.1924     0.0000     -8.6002     -5.5773
DailyAverageWindSpeed                         -1.2589     0.0619    -20.347     0.0000     -1.3802     -1.1376
DailyDepartureFromNormalAverageTemperature     0.8698     0.0286     30.455     0.0000      0.8139      0.9258
DailyMaximumDryBulbTemperature                 0.5708     0.0360     15.840     0.0000      0.5002      0.6414
DailyMinimumDryBulbTemperature                -0.6045     0.0399    -15.149     0.0000     -0.6827     -0.5263
DailyPeakWindSpeed                            -0.8725     0.3867    -2.2566     0.0240     -1.6304     -0.1147
DailyPrecipitation                             0.1140     0.0132     8.6624     0.0000      0.0882      0.1398
DailySustainedWindSpeed                       -0.3651     0.5551    -0.6578     0.5107     -1.4531      0.7228
DailyPeakWindDirection_sin                     1.6191     1.2385     1.3073     0.1911     -0.8083      4.0466
DailyPeakWindDirection_cos                    -2.1659     0.5458    -3.9681     0.0001     -3.2356     -1.0961
DailySustainedWindDirection_sin               -1.0168     0.9813    -1.0362     0.3001     -2.9402      0.9066
DailySustainedWindDirection_cos               -2.8527     0.7697    -3.7064     0.0002     -4.3612     -1.3441
DailyAverageDewPointTemperature                0.9762     4.7116     0.2072     0.8359     -8.2586      10.211
DailyAveragePrecipitation                      3.6783     1.6742     2.1970     0.0280      0.3968      6.9597
DailyAveragePressureChange                     3.1019     3.2670     0.9494     0.3424     -3.3015      9.5052
DailyAverageRelativeHumidity                  -1.0535     0.3082    -3.4182     0.0006     -1.6577     -0.4494
DailyAverageSeaLevelPressure                  -5.5701     0.1257    -44.318     0.0000     -5.8165     -5.3238
DailyAverageStationPressure                    4.7900     0.1765     27.138     0.0000      4.4440      5.1359
DailyAverageWetBulbTemperature                 6.4580     5.3954     1.1970     0.2313     -4.1169      17.033
DailyAverageWindGustSpeed                     -0.7498     0.3066    -2.4450     0.0145     -1.3508     -0.1487
DailyAverageWindDirection_sin                 -3.7683     7.1109    -0.5299     0.5962     -17.706      10.169
DailyAverageWindDirection_cos                 -8.3190     4.3347    -1.9192     0.0550     -16.815      0.1770
Number                                         0.0051     0.0028     1.8403     0.0657     -0.0003      0.0106
Capacity                                      -0.5057     0.3635    -1.3912     0.1642     -1.2182      0.2068
==============================================================================================================

F-test for Poolability: 191.33
P-value: 0.0000
Distribution: F(10,72952)

Included effects: Entity, Time
Saving table...
Table saved successfully

# Lasso Regression

In [ ]:

nonnumeric = {}
nonlist = []
for i in totaldataframe.columns:
    temp = totaldataframe.dropna()
    try:
        temp[i] = pd.to_numeric(totaldataframe[i])
    except:
        nonnumeric[i] = totaldataframe[i].dtypes
        nonlist.append(i)

print(nonnumeric )
print(nonlist)

/var/folders/d1/xmw0d36x7fn39t0jfvtsbzk80000gn/T/ipykernel_77905/1820791694.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp[i] = pd.to_numeric(totaldataframe[i])

['CLIMATE_STATION_NAME',
 'AQ_STATION_NAME',
 'site_address',
 'CLIMATE_STATION_NAME_lag1',
 'DailyDepartureFromNormalAverageTemperature_lag1',
 'DailyMaximumDryBulbTemperature_lag1',
 'DailyMinimumDryBulbTemperature_lag1',
 'AQ_STATION_NAME_lag1',
 'site_address_lag1',
 'CLIMATE_STATION_NAME_lag2',
 'DailyDepartureFromNormalAverageTemperature_lag2',
 'DailyMaximumDryBulbTemperature_lag2',
 'DailyMinimumDryBulbTemperature_lag2',
 'AQ_STATION_NAME_lag2',
 'site_address_lag2',
 'CLIMATE_STATION_NAME_lag3',
 'DailyDepartureFromNormalAverageTemperature_lag3',
 'DailyMaximumDryBulbTemperature_lag3',
 'DailyMinimumDryBulbTemperature_lag3',
 'AQ_STATION_NAME_lag3',
 'site_address_lag3']

In [32]:
keepnonnumeric = ['CLIMATE_STATION_NAME',
 'AQ_STATION_NAME',
 'site_address']

lagdrops = ['CLIMATE_STATION_NAME_lag1','AQ_STATION_NAME_lag1','site_address_lag1','CLIMATE_STATION_NAME_lag2',
           'AQ_STATION_NAME_lag2','site_address_lag2','CLIMATE_STATION_NAME_lag3','AQ_STATION_NAME_lag3',
           'site_address_lag3','site_address', 'LATITUDE', 'LONGITUDE', 'SOURCE','LATITUDE_lag1','LONGITUDE_lag1','SOURCE_lag1']


for i in totaldataframe.columns:
    if ('address' in i) | ('NAME' in i):
        lagdrops.append(i)

lagdrops

['CLIMATE_STATION_NAME_lag1',
 'AQ_STATION_NAME_lag1',
 'site_address_lag1',
 'CLIMATE_STATION_NAME_lag2',
 'AQ_STATION_NAME_lag2',
 'site_address_lag2',
 'CLIMATE_STATION_NAME_lag3',
 'AQ_STATION_NAME_lag3',
 'site_address_lag3',
 'site_address',
 'LATITUDE',
 'LONGITUDE',
 'SOURCE',
 'LATITUDE_lag1',
 'LONGITUDE_lag1',
 'SOURCE_lag1',
 'CLIMATE_STATION_NAME',
 'AQ_STATION_NAME',
 'site_address',
 'CLIMATE_STATION_NAME_lag1',
 'AQ_STATION_NAME_lag1',
 'site_address_lag1',
 'CLIMATE_STATION_NAME_lag2',
 'AQ_STATION_NAME_lag2',
 'site_address_lag2',
 'CLIMATE_STATION_NAME_lag3',
 'AQ_STATION_NAME_lag3',
 'site_address_lag3']

In [24]:
for col in totaldataframe.columns:
    print(f'{col:}:{totaldataframe[col].isna().sum()}')

DATE:0
CLIMATE_STATION_NAME:0
LATITUDE:0
LONGITUDE:0
ELEVATION:0
SOURCE:0
DailyAverageDryBulbTemperature:0
DailyAverageWindSpeed:0
DailyDepartureFromNormalAverageTemperature:68
DailyMaximumDryBulbTemperature:32
DailyMinimumDryBulbTemperature:36
DailyPeakWindSpeed:0
DailyPrecipitation:0
DailySustainedWindSpeed:0
Sunrise:0
Sunset:0
DailyPeakWindDirection_sin:0
DailyPeakWindDirection_cos:0
DailySustainedWindDirection_sin:0
DailySustainedWindDirection_cos:0
DailyAverageAltimeterSetting:0
DailyAverageDewPointTemperature:0
DailyAveragePrecipitation:0
DailyAveragePressureChange:0
DailyAverageRelativeHumidity:0
DailyAverageSeaLevelPressure:0
DailyAverageStationPressure:0
DailyAverageWetBulbTemperature:0
DailyAverageWindGustSpeed:0
DailyAverageWindDirection_sin:0
DailyAverageWindDirection_cos:0
AQlatitude:0
AQlongitude:0
arithmetic_mean:0
first_max_value:0
first_max_hour:0
aqi:0
AQ_STATION_NAME:0
site_address:0
Number:0
Capacity:0
Gross Load (MWh):0
SO2 Mass (short tons):0
CO2 Mass (short tons):0
NOx Mass (short tons):0
BUS_COUNT:0
NUM_READS:0
SPEED:0
YEAR:0
sunrise_sin:0
sunrise_cos:0
sunset_sin:0
sunset_cos:0
DATE_lag1:1
CLIMATE_STATION_NAME_lag1:1
LATITUDE_lag1:1
LONGITUDE_lag1:1
ELEVATION_lag1:1
SOURCE_lag1:1
DailyAverageDryBulbTemperature_lag1:1
DailyAverageWindSpeed_lag1:1
DailyDepartureFromNormalAverageTemperature_lag1:1
DailyMaximumDryBulbTemperature_lag1:1
DailyMinimumDryBulbTemperature_lag1:1
DailyPeakWindSpeed_lag1:1
DailyPrecipitation_lag1:1
DailySustainedWindSpeed_lag1:1
Sunrise_lag1:1
Sunset_lag1:1
DailyPeakWindDirection_sin_lag1:1
DailyPeakWindDirection_cos_lag1:1
DailySustainedWindDirection_sin_lag1:1
DailySustainedWindDirection_cos_lag1:1
DailyAverageAltimeterSetting_lag1:1
DailyAverageDewPointTemperature_lag1:1
DailyAveragePrecipitation_lag1:1
DailyAveragePressureChange_lag1:1
DailyAverageRelativeHumidity_lag1:1
DailyAverageSeaLevelPressure_lag1:1
DailyAverageStationPressure_lag1:1
DailyAverageWetBulbTemperature_lag1:1
DailyAverageWindGustSpeed_lag1:1
DailyAverageWindDirection_sin_lag1:1
DailyAverageWindDirection_cos_lag1:1
AQlatitude_lag1:1
AQlongitude_lag1:1
arithmetic_mean_lag1:1
first_max_value_lag1:1
first_max_hour_lag1:1
aqi_lag1:1
AQ_STATION_NAME_lag1:1
site_address_lag1:1
Number_lag1:1
Capacity_lag1:1
Gross Load (MWh)_lag1:1
SO2 Mass (short tons)_lag1:1
CO2 Mass (short tons)_lag1:1
NOx Mass (short tons)_lag1:1
BUS_COUNT_lag1:1
NUM_READS_lag1:1
SPEED_lag1:1
YEAR_lag1:1
sunrise_sin_lag1:1
sunrise_cos_lag1:1
sunset_sin_lag1:1
sunset_cos_lag1:1
DATE_lag2:2
CLIMATE_STATION_NAME_lag2:2
LATITUDE_lag2:2
LONGITUDE_lag2:2
ELEVATION_lag2:2
SOURCE_lag2:2
DailyAverageDryBulbTemperature_lag2:2
DailyAverageWindSpeed_lag2:2
DailyDepartureFromNormalAverageTemperature_lag2:2
DailyMaximumDryBulbTemperature_lag2:2
DailyMinimumDryBulbTemperature_lag2:2
DailyPeakWindSpeed_lag2:2
DailyPrecipitation_lag2:2
DailySustainedWindSpeed_lag2:2
Sunrise_lag2:2
Sunset_lag2:2
DailyPeakWindDirection_sin_lag2:2
DailyPeakWindDirection_cos_lag2:2
DailySustainedWindDirection_sin_lag2:2
DailySustainedWindDirection_cos_lag2:2
DailyAverageAltimeterSetting_lag2:2
DailyAverageDewPointTemperature_lag2:2
DailyAveragePrecipitation_lag2:2
DailyAveragePressureChange_lag2:2
DailyAverageRelativeHumidity_lag2:2
DailyAverageSeaLevelPressure_lag2:2
DailyAverageStationPressure_lag2:2
DailyAverageWetBulbTemperature_lag2:2
DailyAverageWindGustSpeed_lag2:2
DailyAverageWindDirection_sin_lag2:2
DailyAverageWindDirection_cos_lag2:2
AQlatitude_lag2:2
AQlongitude_lag2:2
arithmetic_mean_lag2:2
first_max_value_lag2:2
first_max_hour_lag2:2
aqi_lag2:2
AQ_STATION_NAME_lag2:2
site_address_lag2:2
Number_lag2:2
Capacity_lag2:2
Gross Load (MWh)_lag2:2
SO2 Mass (short tons)_lag2:2
CO2 Mass (short tons)_lag2:2
NOx Mass (short tons)_lag2:2
BUS_COUNT_lag2:2
NUM_READS_lag2:2
SPEED_lag2:2
YEAR_lag2:2
sunrise_sin_lag2:2
sunrise_cos_lag2:2
sunset_sin_lag2:2
sunset_cos_lag2:2
DATE_lag3:3
CLIMATE_STATION_NAME_lag3:3
LATITUDE_lag3:3
LONGITUDE_lag3:3
ELEVATION_lag3:3
SOURCE_lag3:3
DailyAverageDryBulbTemperature_lag3:3
DailyAverageWindSpeed_lag3:3
DailyDepartureFromNormalAverageTemperature_lag3:3
DailyMaximumDryBulbTemperature_lag3:3
DailyMinimumDryBulbTemperature_lag3:3
DailyPeakWindSpeed_lag3:3
DailyPrecipitation_lag3:3
DailySustainedWindSpeed_lag3:3
Sunrise_lag3:3
Sunset_lag3:3
DailyPeakWindDirection_sin_lag3:3
DailyPeakWindDirection_cos_lag3:3
DailySustainedWindDirection_sin_lag3:3
DailySustainedWindDirection_cos_lag3:3
DailyAverageAltimeterSetting_lag3:3
DailyAverageDewPointTemperature_lag3:3
DailyAveragePrecipitation_lag3:3
DailyAveragePressureChange_lag3:3
DailyAverageRelativeHumidity_lag3:3
DailyAverageSeaLevelPressure_lag3:3
DailyAverageStationPressure_lag3:3
DailyAverageWetBulbTemperature_lag3:3
DailyAverageWindGustSpeed_lag3:3
DailyAverageWindDirection_sin_lag3:3
DailyAverageWindDirection_cos_lag3:3
AQlatitude_lag3:3
AQlongitude_lag3:3
arithmetic_mean_lag3:3
first_max_value_lag3:3
first_max_hour_lag3:3
aqi_lag3:3
AQ_STATION_NAME_lag3:3
site_address_lag3:3
Number_lag3:3
Capacity_lag3:3
Gross Load (MWh)_lag3:3
SO2 Mass (short tons)_lag3:3
CO2 Mass (short tons)_lag3:3
NOx Mass (short tons)_lag3:3
BUS_COUNT_lag3:3
NUM_READS_lag3:3
SPEED_lag3:3
YEAR_lag3:3
sunrise_sin_lag3:3
sunrise_cos_lag3:3
sunset_sin_lag3:3
sunset_cos_lag3:3
MONTH:0

(72984, 213)